-- =====================================================================
-- 007_dataflow.sql — DATAFLOW VẬN HÀNH: batch tracking + rule tổng quát
--
-- VÌ SAO CÓ FILE NÀY (10/07/2026):
--   Pipeline 001–006 là one-shot cho đúng Data_set.xlsx. Khi có chức năng
--   upload (React app ghi thẳng vào raw.*), 7 điểm sẽ gãy:
--     1. Không có đường vào: không batch_id, không rollback, không chặn trùng file
--     2. Orphan hardcode 'KH999'/'VT999' → orphan MỚI không bị gắn cờ
--     3. mart.fact_inventory inner join → âm thầm nuốt dòng orphan mới
--     4. Dashboard 3 có số "đông cứng" (waterfall, error_layer ghi sẵn 97,79%)
--     5. 005_reconcile.sql trộn invariant với số vàng của file gốc
--     6. dim_month sinh từ plan → tháng mới không có plan là biến mất
--     7. item_moc sold_6m cộng TOÀN BỘ lịch sử thay vì cửa sổ 6 tháng
--
-- FILE NÀY THAY THẾ định nghĩa view của 002 + 003 + 006 (tự chứa, chạy
-- lại được). KHÔNG sửa 001/004/005. Chạy xong PHẢI chạy lại 005 → 20/20
-- xanh (dữ liệu gốc không đổi kết quả) + mart.invariant_checks → all ok.
--
-- CHÍNH SÁCH DỮ LIỆU KHI UPLOAD:
--   Mỗi file upload là một SNAPSHOT. Batch loaded có batch_id lớn nhất là
--   snapshot active; toàn bộ stg/mart chỉ đọc snapshot này. Nhờ vậy nếu file
--   mới đã xóa một dòng thì dashboard cũng mất dòng đó, thay vì cộng dồn
--   với batch trước. Batch cũ vẫn giữ trong raw để rollback có đường quay về.
-- =====================================================================


-- =====================================================================
-- A. BATCH TRACKING — đường vào của dữ liệu
-- =====================================================================
create table if not exists raw.load_batches (
  batch_id    bigint generated by default as identity primary key,
  file_name   text not null,
  file_hash   text not null unique,       -- chặn upload trùng nguyên file
  row_counts  jsonb,                      -- {"fact_sales_orders": 452, ...}
  status      text not null default 'loaded'
              check (status in ('loaded','rolled_back')),
  loaded_at   timestamptz not null default now(),
  loaded_by   text
);

-- Batch #1 = seed từ Data_set.xlsx (001b_seed.sql / etl/load.py)
insert into raw.load_batches (batch_id, file_name, file_hash, status, loaded_by)
values (1, 'Data_set.xlsx (seed)', 'seed-001b', 'loaded', 'migration')
on conflict (file_hash) do nothing;
select setval(pg_get_serial_sequence('raw.load_batches','batch_id'),
              greatest((select max(batch_id) from raw.load_batches), 1));

-- batch_id trên mọi bảng raw. Đây là LINEAGE, không phải business data —
-- không vi phạm nguyên tắc "raw 0 constraint": FK về metadata không chặn
-- được bất kỳ dữ liệu bẩn nghiệp vụ nào.
alter table raw.fact_sales_orders  add column if not exists batch_id bigint not null default 1;
alter table raw.fact_inventory_eom add column if not exists batch_id bigint not null default 1;
alter table raw.dim_product        add column if not exists batch_id bigint not null default 1;
alter table raw.dim_customer       add column if not exists batch_id bigint not null default 1;
alter table raw.dim_warehouse      add column if not exists batch_id bigint not null default 1;
alter table raw.plan_monthly_sales add column if not exists batch_id bigint not null default 1;
alter table raw.data_quality_hint  add column if not exists batch_id bigint not null default 1;

do $$
declare t text;
begin
  foreach t in array array['fact_sales_orders','fact_inventory_eom','dim_product',
                           'dim_customer','dim_warehouse','plan_monthly_sales',
                           'data_quality_hint']
  loop
    if not exists (
      select 1 from pg_constraint
      where conname = t || '_batch_fk' and connamespace = 'raw'::regnamespace
    ) then
      execute format(
        'alter table raw.%I add constraint %I foreign key (batch_id)
         references raw.load_batches(batch_id)', t, t || '_batch_fk');
    end if;
  end loop;
end $$;

-- Rollback một lần upload hỏng. SECURITY DEFINER để client (anon) gọi
-- được qua RPC mà không cần quyền DELETE trực tiếp trên raw.
create or replace function raw.rollback_batch(p_batch_id bigint)
returns jsonb
language plpgsql security definer set search_path = raw
as $$
declare
  n bigint; deleted jsonb := '{}'::jsonb;
begin
  if p_batch_id = 1 then
    raise exception 'Không thể rollback batch seed #1';
  end if;
  if not exists (select 1 from raw.load_batches
                 where batch_id = p_batch_id and status = 'loaded') then
    raise exception 'Batch % không tồn tại hoặc đã rollback', p_batch_id;
  end if;

  delete from raw.fact_sales_orders  where batch_id = p_batch_id;
  get diagnostics n = row_count; deleted := deleted || jsonb_build_object('fact_sales_orders', n);
  delete from raw.fact_inventory_eom where batch_id = p_batch_id;
  get diagnostics n = row_count; deleted := deleted || jsonb_build_object('fact_inventory_eom', n);
  delete from raw.dim_product        where batch_id = p_batch_id;
  get diagnostics n = row_count; deleted := deleted || jsonb_build_object('dim_product', n);
  delete from raw.dim_customer       where batch_id = p_batch_id;
  get diagnostics n = row_count; deleted := deleted || jsonb_build_object('dim_customer', n);
  delete from raw.dim_warehouse      where batch_id = p_batch_id;
  get diagnostics n = row_count; deleted := deleted || jsonb_build_object('dim_warehouse', n);
  delete from raw.plan_monthly_sales where batch_id = p_batch_id;
  get diagnostics n = row_count; deleted := deleted || jsonb_build_object('plan_monthly_sales', n);
  delete from raw.data_quality_hint  where batch_id = p_batch_id;
  get diagnostics n = row_count; deleted := deleted || jsonb_build_object('data_quality_hint', n);

  update raw.load_batches set status = 'rolled_back' where batch_id = p_batch_id;
  return jsonb_build_object('batch_id', p_batch_id, 'deleted', deleted);
end $$;


-- =====================================================================
-- B. STG — dựng lại với rule TỔNG QUÁT (thay thế 002_stg.sql)
-- =====================================================================
drop schema if exists stg cascade;
create schema stg;

-- ---------------------------------------------------------------------
-- Active raw snapshot: stg/mart chỉ đọc file upload gần nhất còn loaded.
-- ---------------------------------------------------------------------
create view stg.active_batch as
select max(batch_id) as batch_id
from raw.load_batches
where status = 'loaded';

create view stg.raw_fact_sales_orders as
select f.*
from raw.fact_sales_orders f
join stg.active_batch b on b.batch_id = f.batch_id;

create view stg.raw_fact_inventory_eom as
select f.*
from raw.fact_inventory_eom f
join stg.active_batch b on b.batch_id = f.batch_id;

create view stg.raw_dim_product as
select d.*
from raw.dim_product d
join stg.active_batch b on b.batch_id = d.batch_id;

create view stg.raw_dim_customer as
select d.*
from raw.dim_customer d
join stg.active_batch b on b.batch_id = d.batch_id;

create view stg.raw_dim_warehouse as
select d.*
from raw.dim_warehouse d
join stg.active_batch b on b.batch_id = d.batch_id;

create view stg.raw_plan_monthly_sales as
select p.*
from raw.plan_monthly_sales p
join stg.active_batch b on b.batch_id = p.batch_id;

-- ---------------------------------------------------------------------
-- Dimensions: trong snapshot active, vẫn chống trùng mã bằng dòng mới nhất
-- ---------------------------------------------------------------------
create view stg.dim_product_current as
select distinct on (item_code)
  item_code, item_name, category_code, category_name,
  standard_cost, list_price, item_status, abc_class, launch_date, batch_id
from stg.raw_dim_product
order by item_code, batch_id desc;

create view stg.dim_customer_current as
select distinct on (customer_code)
  customer_code, customer_name, region, channel, salesperson, customer_status, batch_id
from stg.raw_dim_customer
order by customer_code, batch_id desc;

create view stg.dim_warehouse_current as
select distinct on (warehouse_code)
  warehouse_code, warehouse_name, region, warehouse_status, batch_id
from stg.raw_dim_warehouse
order by warehouse_code, batch_id desc;

-- Member "(Unknown)" sinh ĐỘNG từ mọi mã orphan thực tế trong fact —
-- hết hardcode KH999/VT999 (điểm gãy #2). Với dữ liệu gốc, kết quả giống
-- hệt cũ: đúng 1 unknown product (VT999) + 1 unknown customer (KH999).
create view stg.dim_product as
select item_code, item_name, category_code, category_name,
       standard_cost, list_price, item_status, abc_class, launch_date,
       false as is_unknown
from stg.dim_product_current
union all
select f.item_code, '(Unknown Item)', '(Unknown)', '(Unknown)',
       null, null, 'Unknown', '(Unknown)', null,   -- standard_cost NULL CỐ Ý (bẫy GM%)
       true
from (select item_code from stg.raw_fact_sales_orders
      union
      select item_code from stg.raw_fact_inventory_eom) f
where f.item_code is not null
  and not exists (select 1 from stg.dim_product_current d
                  where d.item_code = f.item_code);

create view stg.dim_customer as
select customer_code, customer_name, region, channel, salesperson, customer_status,
       false as is_unknown
from stg.dim_customer_current
union all
select distinct f.customer_code, '(Unknown Customer)', '(Unknown)', '(Unknown)',
       '(Unknown)', 'Unknown', true
from stg.raw_fact_sales_orders f
where f.customer_code is not null
  and not exists (select 1 from stg.dim_customer_current d
                  where d.customer_code = f.customer_code);

create view stg.dim_warehouse as
select warehouse_code, warehouse_name,
       region as warehouse_region,   -- ⚠️ ĐỔI TÊN. Chống nhầm với dim_customer.region
       warehouse_status,
       false as is_unknown
from stg.dim_warehouse_current
union all
select f.warehouse_code, '(Unknown Warehouse)', '(Unknown)', 'Unknown', true
from (select warehouse_code from stg.raw_fact_sales_orders
      union
      select warehouse_code from stg.raw_fact_inventory_eom) f
where f.warehouse_code is not null
  and not exists (select 1 from stg.dim_warehouse_current d
                  where d.warehouse_code = f.warehouse_code);

-- ---------------------------------------------------------------------
-- FACT SALES — snapshot active + dedupe toàn-cột, cờ orphan tổng quát
-- ---------------------------------------------------------------------
create view stg.fact_sales as
with dup as (
  -- Rule tái sử dụng được: trùng TOÀN BỘ 14 cột nghiệp vụ (bỏ note, bỏ batch).
  -- Bản ở batch cũ hơn / dòng sớm hơn thắng ⇒ re-upload nhầm file fact cũ
  -- sẽ tự bị loại sạch ở mart (mọi dòng thành bản trùng thứ 2).
  select batch_id, src_row_index,
         count(*) over (partition by
           doc_date, order_no, line_no, customer_code, item_code, warehouse_code,
           qty_order, qty_delivered, unit_price, discount_pct, doc_status,
           delivery_due_date, actual_delivery_date
         ) as n_identical,
         row_number() over (partition by
           doc_date, order_no, line_no, customer_code, item_code, warehouse_code,
           qty_order, qty_delivered, unit_price, discount_pct, doc_status,
           delivery_due_date, actual_delivery_date
           order by batch_id, src_row_index
         ) as rn
  from stg.raw_fact_sales_orders
)
select
  row_number() over (order by f.batch_id, f.src_row_index) as sales_sk,   -- H1
  f.batch_id,
  f.src_row_index,
  f.doc_date,
  date_trunc('month', f.doc_date)::date as month_start,
  f.order_no, f.line_no,
  f.customer_code, f.item_code, f.warehouse_code,
  f.qty_order, f.qty_delivered, f.unit_price, f.discount_pct,
  f.doc_status, f.delivery_due_date, f.actual_delivery_date,
  f.salesperson,                       -- ⚠️ NV BÁN ĐƠN NÀY (§8.1 quyết định #3)
  f.note,

  -- ===== 5 cờ DQ (tầng DỮ LIỆU). Với dữ liệu gốc: tổng = 10 dòng =====
  (d.n_identical > 1)                              as flag_dup_row,
  (d.n_identical > 1 and d.rn > 1)                 as flag_dup_delete,
  (c.customer_code is null)                        as flag_orphan_customer,
  (p.item_code is null)                            as flag_orphan_item,
  (w.warehouse_code is null)                       as flag_orphan_warehouse,
  (c.customer_code is null or p.item_code is null
    or w.warehouse_code is null)                   as flag_orphan_fk,   -- TỔNG QUÁT
  (f.unit_price = 0)                               as flag_zero_price,
  (f.discount_pct > 0.20)                          as flag_high_discount,
  (f.order_no ~ '(9999|0000)$')                    as flag_sentinel,

  -- ===== Cờ Process Violation (tầng QUY TRÌNH) — TÁCH RIÊNG (§6.2) =====
  -- Dòng dữ liệu HOÀN TOÀN ĐÚNG. Cái sai là hành vi bán hàng.
  (p.item_status      = 'Discontinued')            as flag_pv_discontinued_item,
  (c.customer_status  = 'Inactive')                as flag_pv_inactive_customer,
  (w.warehouse_status = 'Inactive')                as flag_pv_inactive_warehouse,
  (coalesce(p.item_status,'')        = 'Discontinued'
    or coalesce(c.customer_status,'')  = 'Inactive'
    or coalesce(w.warehouse_status,'') = 'Inactive') as flag_process_violation
from stg.raw_fact_sales_orders f
join dup d on d.batch_id = f.batch_id and d.src_row_index = f.src_row_index
left join stg.dim_product_current   p on p.item_code      = f.item_code
left join stg.dim_customer_current  c on c.customer_code  = f.customer_code
left join stg.dim_warehouse_current w on w.warehouse_code = f.warehouse_code;

-- ---------------------------------------------------------------------
-- FACT INVENTORY — trong snapshot active, chống trùng theo khóa tự nhiên
-- ---------------------------------------------------------------------
create view stg.fact_inventory as
with latest as (
  select distinct on (month_end, item_code, warehouse_code) *
  from stg.raw_fact_inventory_eom
  order by month_end, item_code, warehouse_code, batch_id desc
)
select
  i.batch_id,
  i.month_end,
  i.item_code, i.warehouse_code,
  i.on_hand_qty,
  i.inventory_value,       -- giữ để reconcile §6.6, KHÔNG đưa lên mart
  i.safety_stock,
  -- H6: Excel serial epoch = 1899-12-30 (KHÔNG phải 1900-01-01)
  (date '1899-12-30' + (i.last_receipt_serial || ' days')::interval)::date
                                             as last_receipt_date,
  i.last_receipt_serial,
  i.stock_status_note,
  (i.on_hand_qty < 0)                        as flag_negative_stock,
  (p.item_code is null)                      as flag_orphan_item,
  (w.warehouse_code is null)                 as flag_orphan_warehouse,
  (p.item_code is null or w.warehouse_code is null) as flag_orphan_fk,  -- TỔNG QUÁT
  (i.on_hand_qty < i.safety_stock)           as flag_below_safety
from latest i
left join stg.dim_product_current   p on p.item_code      = i.item_code
left join stg.dim_warehouse_current w on w.warehouse_code = i.warehouse_code;

comment on schema stg is
  'Cast kiểu, surrogate key, gắn cờ — rule TỔNG QUÁT, chạy được với mọi batch. '
  'stg/mart chỉ đọc batch loaded mới nhất như một snapshot active. '
  'Fact sales: dedupe toàn-cột trong snapshot. Xem 007_dataflow.sql.';


-- =====================================================================
-- C. MART — dựng lại (thay thế 003_mart.sql + 006_mart_audit.sql)
-- =====================================================================
drop schema if exists mart cascade;
create schema mart;

-- Điểm gãy #6: dim_month lấy union tháng từ CẢ BA nguồn, không chỉ plan
create view mart.dim_month as
with m as (
  -- Excel/seed plan có thể lưu ngày cuối tháng trước (vd 2025-12-31
  -- cho plan 01/2026). Cộng 1 ngày rồi truncate để đưa về tháng kế hoạch.
  select distinct date_trunc('month', month_start + interval '1 day')::date as month_start
  from stg.raw_plan_monthly_sales
  union
  select distinct date_trunc('month', doc_date)::date from stg.raw_fact_sales_orders
  union
  select distinct date_trunc('month', month_end)::date from stg.raw_fact_inventory_eom
)
select
  month_start,
  (month_start + interval '1 month - 1 day')::date as month_end,
  to_char(month_start, 'MM/YYYY')                  as month_label,
  extract(month from month_start)::int             as month_number,
  extract(year  from month_start)::int             as year_number
from m
where month_start is not null;

create view mart.dim_market_region as
-- ⚠️ VÙNG KHÁCH HÀNG. Dashboard 1 dùng cái này.
-- Dashboard 2 dùng dim_warehouse.warehouse_region — KHÁC HẲN. 65,7% dòng lệch.
select distinct region as market_region, (region = '(Unknown)') as is_unknown
from stg.dim_customer;

create view mart.dim_category as
select distinct category_code, category_name, (category_code = '(Unknown)') as is_unknown
from stg.dim_product;

create view mart.dim_product   as select * from stg.dim_product;
create view mart.dim_customer  as select * from stg.dim_customer;
create view mart.dim_warehouse as select * from stg.dim_warehouse;

-- Plan: trong snapshot active, chống trùng theo grain
create view mart.plan_monthly as
with normalized as (
  select
    date_trunc('month', month_start + interval '1 day')::date as month_start,
    region,
    category_code,
    category_name,
    target_revenue,
    batch_id
  from stg.raw_plan_monthly_sales
)
select distinct on (month_start, region, category_code)
  month_start, region as market_region, category_code, category_name,
  target_revenue, batch_id
from normalized
order by month_start, region, category_code, batch_id desc;

-- Danh sách batch cho UI (đọc từ mart, không cần đụng raw)
create view mart.load_batches as
select
  batch_id, file_name, file_hash, row_counts, status, loaded_at, loaded_by,
  (batch_id = (select batch_id from stg.active_batch)) as is_active
from raw.load_batches;

-- ---------------------------------------------------------------------
-- FACT SALES — 450 dòng với dữ liệu gốc
-- ⚠️ TUYỆT ĐỐI KHÔNG: select distinct on (order_no, line_no)
--    Làm vậy mất 293.054.650 VNĐ (−5,63%). Xem 005 assert #16.
-- ---------------------------------------------------------------------
create view mart.fact_sales as
select
  sales_sk, batch_id, src_row_index, doc_date, month_start,
  order_no, line_no,
  customer_code, item_code, warehouse_code,
  qty_order, qty_delivered, unit_price, discount_pct,
  doc_status, delivery_due_date, actual_delivery_date, salesperson,
  qty_delivered * unit_price * (1 - discount_pct) as line_revenue,
  -- in_plan_scope TỔNG QUÁT: dòng có khách VÀ item thật (orphan không có
  -- region/category nên nằm ngoài grain plan). Dữ liệu gốc: loại đúng
  -- KH999 + VT999 → 5.134.128.150 / 84.602.000.000 = 6,07% (397 dòng)
  (not flag_orphan_customer and not flag_orphan_item) as in_plan_scope,
  flag_orphan_fk, flag_zero_price, flag_high_discount,
  flag_process_violation, flag_pv_discontinued_item,
  flag_pv_inactive_customer, flag_pv_inactive_warehouse
from stg.fact_sales
where not flag_dup_delete      -- bỏ bản trùng thứ 2 (dữ liệu gốc: index 450)
  and not flag_sentinel;       -- bỏ dòng sentinel   (dữ liệu gốc: index 451)

-- ---------------------------------------------------------------------
-- FACT INVENTORY — điểm gãy #3: LEFT JOIN + giữ dòng orphan kèm cờ.
-- Orphan mới không còn bị nuốt âm thầm; measure loại orphan TƯỜNG MINH
-- bằng flag_orphan_fk. inventory_value của orphan = NULL (không có cost).
-- ---------------------------------------------------------------------
create view mart.fact_inventory as
select
  i.batch_id,
  i.month_end,
  date_trunc('month', i.month_end)::date as month_start,
  i.item_code, i.warehouse_code,
  i.on_hand_qty,                                    -- GIỮ NGUYÊN ÂM. Không set = 0
  i.safety_stock,
  i.last_receipt_date,
  (i.month_end - i.last_receipt_date)               as days_since_receipt,
  i.on_hand_qty * p.standard_cost                   as inventory_value,
  (i.month_end = (select max(month_end) from stg.fact_inventory))
                                                    as is_latest_eom,
  i.flag_negative_stock,
  i.flag_orphan_fk,
  i.flag_below_safety
from stg.fact_inventory i
left join stg.dim_product_current p on p.item_code = i.item_code;

-- ---------------------------------------------------------------------
-- ITEM MOC — điểm gãy #7: sold_6m = cửa sổ 6 THÁNG GẦN NHẤT tính từ
-- snapshot EOM mới nhất, không phải toàn bộ lịch sử.
--
-- ⚠️ Ba filter doc_status khác nhau trong cùng model (ERRATA E2):
--    Revenue Net : <> 'Cancelled'  ·  Fill Rate: IN (Completed, Open)
--    sold_6m/MOC : IN (Completed, Return)   <-- CÁI NÀY
-- ---------------------------------------------------------------------
create view mart.item_moc as
with maxm as (
  select max(month_end) as month_end from mart.fact_inventory
),
eom as (
  select item_code,
         sum(on_hand_qty)     as on_hand_eom,
         sum(inventory_value) as inv_value_eom
  from mart.fact_inventory
  where month_end = (select month_end from maxm)
    and not flag_orphan_fk
  group by item_code
),
sold as (
  select item_code, sum(qty_delivered) as sold_6m
  from mart.fact_sales
  where doc_status in ('Completed','Return')     -- trừ hàng trả lại
    and doc_date > (select month_end from maxm) - interval '6 months'
  group by item_code
),
med as (
  select percentile_cont(0.5) within group (order by inv_value_eom) as median_inv_value
  from eom
)
select
  e.item_code,
  p.item_name, p.category_name, p.abc_class, p.item_status,
  e.on_hand_eom,
  e.inv_value_eom,
  coalesce(s.sold_6m, 0)                                          as sold_6m,
  -- BLANK (null) khi sold_6m = 0, không phải vô cực
  case when coalesce(s.sold_6m,0) > 0
       then e.on_hand_eom / (s.sold_6m / 6.0) end                 as moc,
  m.median_inv_value,
  -- ĐIỀU KIỆN KÉP (§5.2). Xếp hạng chỉ theo MOC cho cảnh báo sai:
  -- VT033 có MOC 65,7 (cao nhất) nhưng chỉ 72,8 tr vốn.
  ( e.inv_value_eom > m.median_inv_value
    and coalesce(s.sold_6m,0) > 0
    and e.on_hand_eom / (s.sold_6m / 6.0) > 12 )                  as is_slow_heavy
from eom e
cross join med m
join stg.dim_product_current p on p.item_code = e.item_code
left join sold s               on s.item_code = e.item_code;

-- ---------------------------------------------------------------------
-- DQ layer cho Dashboard 3 (từ 006, thêm batch_id + cờ tổng quát).
-- ⚠️ mart.fact_sales (sạch) và mart.dq_fact_sales (nguyên trạng) KHÔNG
--    được join với nhau ở tầng UI. Điều 9 CLAUDE.md.
-- ---------------------------------------------------------------------
create view mart.dq_fact_sales as
select
  sales_sk, batch_id, src_row_index, doc_date, month_start,
  order_no, line_no, customer_code, item_code, warehouse_code,
  qty_order, qty_delivered, unit_price, discount_pct,
  doc_status, salesperson,
  flag_dup_row, flag_orphan_fk, flag_zero_price,
  flag_high_discount, flag_sentinel,
  (flag_dup_row or flag_orphan_fk or flag_zero_price
    or flag_high_discount or flag_sentinel)      as flag_dq_dirty,
  flag_pv_discontinued_item, flag_pv_inactive_customer,
  flag_pv_inactive_warehouse, flag_process_violation,
  case
    when flag_dup_row          then 'Dòng trùng (14 cột giống hệt)'
    when flag_orphan_fk        then 'Orphan FK (mã không có trong dim)'
    when flag_zero_price       then 'UnitPrice = 0'
    when flag_high_discount    then 'DiscountPct > 20%'
    when flag_sentinel         then 'Mã đơn sentinel 9999/0000'
  end as dq_issue,
  case
    when flag_pv_discontinued_item  then 'Bán hàng Discontinued'
    when flag_pv_inactive_customer  then 'Bán cho khách Inactive'
    when flag_pv_inactive_warehouse then 'Xuất từ kho ngừng hoạt động'
  end as pv_issue
from stg.fact_sales;

create view mart.dq_fact_inventory as
select
  batch_id, month_end, item_code, warehouse_code,
  on_hand_qty, safety_stock, last_receipt_date,
  inventory_value as inventory_value_raw,
  flag_negative_stock, flag_orphan_fk, flag_below_safety,
  (flag_negative_stock or flag_orphan_fk) as flag_dq_dirty
from stg.fact_inventory;

create view mart.dq_inventory_recon as
select
  i.month_end, i.item_code, i.warehouse_code,
  i.inventory_value                          as value_reported,
  i.on_hand_qty * p.standard_cost            as value_recomputed,
  (i.inventory_value = i.on_hand_qty * p.standard_cost) as is_match
from stg.fact_inventory i
left join stg.dim_product_current p using (item_code);

-- ---------------------------------------------------------------------
-- Điểm gãy #4: WATERFALL tính ĐỘNG từ dữ liệu (thay bảng tĩnh
-- audit.waterfall_step). Với dữ liệu gốc ra đúng số cũ:
--   A +5.463.412.100 · B −11.956.000 · C −135.000.000 · D −107.785.450
--   E = 5.208.670.650
-- ---------------------------------------------------------------------
create view mart.audit_waterfall as
with s as (
  select *, qty_delivered * unit_price * (1 - discount_pct) as rev
  from stg.fact_sales
)
select 1 as step_order, 'A' as step_code,
       'Gross Revenue (Completed + Open, gồm mọi lỗi)' as step_name,
       (select coalesce(sum(rev),0) from s
        where doc_status in ('Completed','Open'))::numeric as amount,
       false as is_total
union all
select 2, 'B', 'Trừ dòng trùng thật',
       -(select coalesce(sum(rev),0) from s
         where flag_dup_delete and doc_status <> 'Cancelled'), false
union all
select 3, 'C', 'Trừ dòng sentinel / bất khả thi vật lý',
       -(select coalesce(sum(rev),0) from s
         where flag_sentinel and not flag_dup_delete
           and doc_status <> 'Cancelled'), false
union all
select 4, 'D', 'Trừ hàng trả lại (Return)',
       (select coalesce(sum(rev),0) from s
        where doc_status = 'Return'
          and not flag_dup_delete and not flag_sentinel), false
union all
select 5, 'E', 'Revenue Net',
       (select coalesce(sum(line_revenue),0) from mart.fact_sales
        where doc_status <> 'Cancelled'), true;

-- Điểm gãy #4 (tiếp): error_layer với chỉ số tính ĐỘNG, hết ghi cứng 97,79%
create view mart.audit_error_layer as
with dq as (
  select round(100*(1 - count(*) filter (where flag_dup_row or flag_orphan_fk
              or flag_zero_price or flag_high_discount or flag_sentinel)::numeric
              / nullif(count(*),0)), 2) as dq_so
  from stg.fact_sales
),
dqi as (
  select round(100*(1 - count(*) filter (where flag_negative_stock or flag_orphan_fk)::numeric
              / nullif(count(*),0)), 2) as dq_inv
  from stg.fact_inventory
),
pv as (
  select round(100.0*count(*) filter (where flag_process_violation)
              / nullif(count(*),0), 2) as pv
  from stg.fact_sales
)
select 1 as layer_order, 'Dữ liệu' as layer,
       'Có ghi đúng cái đã xảy ra không?' as question,
       'unit_price = 0, dòng trùng, orphan FK' as example,
       'DQ Score SO = ' || (select dq_so from dq) || '% · INV = '
         || (select dq_inv from dqi) || '%' as metric,
       'Người nhập liệu / ETL' as owner
union all
select 2, 'Quy trình', 'Cái đã xảy ra có được phép không?',
       'Bán hàng Discontinued, bán cho khách Inactive',
       'PV Score = ' || (select pv from pv) || '%',
       'Quản lý bán hàng'
union all
select 3, 'Thiết kế', 'Hệ thống có đúng không?',
       'Không có khóa tự nhiên · date sai kiểu · plan khác phạm vi',
       'Không đo bằng % — liệt kê',
       'IT / kiến trúc dữ liệu';

-- Các bảng narrative giữ TĨNH (nội dung phân tích, không suy ra từ dữ liệu)
create view mart.audit_rules      as select * from audit.rule_definitions;
create view mart.audit_dq_results as select * from audit.dq_results;

create table mart.audit_issues (
  issue_no      int primary key,
  in_hint       boolean not null,
  issue         text not null,
  source_table  text,
  rows_affected text,
  money_impact  text,
  resolution    text,
  future_rule   text
);

insert into mart.audit_issues values
(1,  false, 'Không có khóa tự nhiên. OrderNo/LineNo không phải khóa (97,6% đơn nhiều dòng có >1 khách)',
     'SO', 'toàn bộ', '−293,1 tr nếu dedupe sai',
     'Sinh surrogate key ở ETL. KHÔNG dedupe theo OrderNo+LineNo', 'H1'),
(2,  true,  'Dòng trùng thật — SO2602-0137|1, giống cả 14 cột',
     'SO', '2', '−11.956.000', 'Xóa 1 bản (src_row_index 450)', 'H2'),
(3,  true,  'Orphan FK — KH999 (3 dòng), VT999 (2 dòng SO + 1 dòng INV)',
     'SO, INV', '5 + 1', '74,5 tr rơi ngoài grain plan',
     'Thêm member "Unknown" vào dim. KHÔNG xóa dòng fact', 'H3'),
(4,  true,  'UnitPrice = 0 — SO2606-0087, NV An',
     'SO', '1', 'Biên âm', 'Cách ly khỏi phân tích giá/biên', 'H4'),
(5,  true,  'DiscountPct = 65% — SO2601-0088, NV Bình (P95 = P99 = 10%)',
     'SO', '1', 'Biên âm; 917.700 VNĐ', 'Cách ly + yêu cầu duyệt', 'S1'),
(6,  true,  'QtyOrder = 900 — BẤT KHẢ THI VẬT LÝ. Kho WH_HCM chưa bao giờ giữ quá 300 đv VT005',
     'SO', '1', '−135.000.000', 'Loại bỏ có căn cứ, không winsorize', 'H7 + H9'),
(7,  true,  'Tồn âm — 14 dòng, 4 dòng còn âm tại 30/06/2026. VT018 âm ở 2 kho',
     'INV', '14', 'Không thể tồn âm vật lý', 'Điều tra nghiệp vụ. KHÔNG set = 0', 'H5'),
(8,  true,  'LastReceiptDate là Excel serial number, không phải date (45.816 → 46.198)',
     'INV', '865', 'Mọi phân tích aging sai', 'Convert bắt buộc trước mọi bước khác', 'H6'),
(9,  false, 'fact.Salesperson ≠ dim_customer.Salesperson ở 344/452 dòng (76%)',
     'SO', '344', 'Báo cáo hiệu suất NV sai hoàn toàn',
     'Chốt định nghĩa: fact = NV bán đơn; dim = NV phụ trách KH', 'D1'),
(10, false, 'Plan và fact không cùng phạm vi — fact là mẫu ~6%, lệch 16,48×',
     'PLAN', '108 ô', 'KPI % đạt kế hoạch không đọc được',
     'Dùng Achievement Index (chuẩn hóa = 100)', 'D2'),
(11, false, 'InventoryValue là cột dẫn xuất = OnHandQty × StandardCost (khớp 864/865)',
     'INV', '865', 'Cột thừa; sửa Qty phải sửa Value',
     'Không lưu; tính lại bằng measure', 'D3');

-- Ba kịch bản làm sạch (động, giữ từ 006)
create view mart.cleaning_scenarios as
with correct as (
  select sum(line_revenue) v from mart.fact_sales where doc_status <> 'Cancelled'
),
nothing as (
  select sum(qty_delivered*unit_price*(1-discount_pct)) v
  from stg.fact_sales where doc_status <> 'Cancelled'
),
bad_dedupe as (
  select sum(qty_delivered*unit_price*(1-discount_pct)) v
  from (select distinct on (order_no, line_no) *
        from stg.fact_sales where not flag_sentinel
        order by order_no, line_no, batch_id, src_row_index) b
  where doc_status <> 'Cancelled'
)
select 1 as scenario_order, 'Làm sạch ĐÚNG'  as scenario, (select v from correct)    as revenue_net, 0.0 as bias_pct, true  as is_correct
union all
select 2, 'KHÔNG làm sạch gì', (select v from nothing),
       round(100*((select v from nothing)-(select v from correct))/(select v from correct), 2), false
union all
select 3, 'Dedupe máy móc theo OrderNo+LineNo', (select v from bad_dedupe),
       round(100*((select v from bad_dedupe)-(select v from correct))/(select v from correct), 2), false;

comment on schema mart is
  'Lớp UI/BI đọc. Rule tổng quát cho mọi batch upload. Đã loại bản trùng thứ 2 '
  'và dòng sentinel. KHÔNG dedupe theo order_no+line_no. Xem 007_dataflow.sql.';


-- =====================================================================
-- D. INVARIANTS — điểm gãy #5: bất biến phải đúng với MỌI dữ liệu
--    (khác 005_reconcile.sql = số vàng CHỈ đúng với Data_set.xlsx gốc).
--    UI gọi sau mỗi lần upload: select * from mart.invariant_checks;
-- =====================================================================
create view mart.invariant_checks as
with w as (
  select
    (select sum(amount) from mart.audit_waterfall where not is_total) as steps_sum,
    (select amount     from mart.audit_waterfall where is_total)      as total
)
select 1 as no,
       'stg.fact_sales bảo toàn số dòng snapshot active (không xóa ở tầng cờ)' as invariant,
       (select count(*) from stg.fact_sales) = (select count(*) from stg.raw_fact_sales_orders) as ok,
       (select count(*) from stg.fact_sales)::text || ' / ' ||
       (select count(*) from stg.raw_fact_sales_orders)::text as detail
union all
select 2, 'mart.fact_sales = stg − (bản trùng thứ 2 + sentinel)',
       (select count(*) from mart.fact_sales) =
       (select count(*) from stg.fact_sales where not flag_dup_delete and not flag_sentinel),
       (select count(*) from mart.fact_sales)::text
union all
select 3, 'Mọi FK của fact_sales resolve qua dim (kể cả member Unknown)',
       not exists (
         select 1 from mart.fact_sales f
         where not exists (select 1 from stg.dim_customer  c where c.customer_code  = f.customer_code)
            or not exists (select 1 from stg.dim_product   p where p.item_code      = f.item_code)
            or not exists (select 1 from stg.dim_warehouse w where w.warehouse_code = f.warehouse_code)
       ),
       'orphan phải được sinh member (Unknown) động'
union all
select 4, 'Mọi FK của fact_inventory resolve qua dim (kể cả Unknown)',
       not exists (
         select 1 from mart.fact_inventory f
         where not exists (select 1 from stg.dim_product   p where p.item_code      = f.item_code)
            or not exists (select 1 from stg.dim_warehouse w where w.warehouse_code = f.warehouse_code)
       ),
       ''
union all
select 5, 'dim_month phủ mọi tháng của sales + inventory + plan',
       not exists (
         select 1 from (
           select distinct month_start from mart.fact_sales
           union select distinct month_start from mart.fact_inventory
           union select distinct month_start from mart.plan_monthly
         ) t
         where not exists (select 1 from mart.dim_month m where m.month_start = t.month_start)
       ),
       (select count(*) from mart.dim_month)::text || ' tháng'
union all
select 6, 'Waterfall khớp: A+B+C+D = Revenue Net',
       (select abs(steps_sum - total) < 0.01 from w),
       (select steps_sum::bigint::text || ' vs ' || total::bigint::text from w)
union all
select 7, 'Grain plan duy nhất (month × region × category)',
       (select count(*) from mart.plan_monthly) =
       (select count(distinct (month_start, market_region, category_code)) from mart.plan_monthly),
       (select count(*) from mart.plan_monthly)::text || ' ô'
union all
select 8, 'Grain inventory duy nhất (month_end × item × warehouse)',
       (select count(*) from stg.fact_inventory) =
       (select count(distinct (month_end, item_code, warehouse_code)) from stg.fact_inventory),
       (select count(*) from stg.fact_inventory)::text || ' dòng'
union all
select 9, 'item_moc phủ mọi item non-orphan trong snapshot mới nhất',
       not exists (
         select 1 from mart.fact_inventory f
         where f.is_latest_eom and not f.flag_orphan_fk
           and not exists (select 1 from mart.item_moc m where m.item_code = f.item_code)
       ),
       (select count(*) from mart.item_moc)::text || ' item'
union all
select 10, 'cleaning_scenarios kịch bản ĐÚNG = Revenue Net',
       (select revenue_net from mart.cleaning_scenarios where scenario_order = 1) =
       (select sum(line_revenue) from mart.fact_sales where doc_status <> 'Cancelled'),
       ''
union all
select 11, 'Snapshot active thuộc batch loaded mới nhất (lineage)',
       not exists (
         select 1
         from stg.raw_fact_sales_orders f
         where f.batch_id <> (select batch_id from stg.active_batch)
       ),
       coalesce((select batch_id::text from stg.active_batch), 'no loaded batch');


-- =====================================================================
-- E. GRANTS + EXPOSE cho web (demo — anon được INSERT vào raw)
-- =====================================================================
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'pbi_reader') then
    create role pbi_reader login password 'CHANGE_ME';
  end if;
end $$;

-- Đọc: mart cho mọi client
grant usage  on schema mart to pbi_reader, anon, authenticated;
grant select on all tables in schema mart to pbi_reader, anon, authenticated;
alter default privileges in schema mart
  grant select on tables to pbi_reader, anon, authenticated;

-- Ghi: raw cho web upload (demo — người dùng đã chốt không cần bảo vệ key)
grant usage on schema raw to anon, authenticated;
grant select, insert on all tables in schema raw to anon, authenticated;
grant usage, select on all sequences in schema raw to anon, authenticated;
grant execute on function raw.rollback_batch(bigint) to anon, authenticated;

-- PostgREST: expose mart (đọc) + raw (ghi)
alter role authenticator set pgrst.db_schemas = 'public, graphql_public, mart, raw';
notify pgrst, 'reload config';


-- =====================================================================
-- F. RLS — các bảng raw gốc đang BẬT RLS (Supabase advisor) nhưng không
--    có policy ⇒ anon bị chặn INSERT dù đã grant. Demo: policy mở cho
--    anon/authenticated. Khi cần siết lại chỉ việc sửa các policy này.
-- =====================================================================
do $$
declare t text;
begin
  foreach t in array array['fact_sales_orders','fact_inventory_eom','dim_product',
                           'dim_customer','dim_warehouse','plan_monthly_sales',
                           'data_quality_hint','load_batches']
  loop
    execute format('alter table raw.%I enable row level security', t);
    execute format('drop policy if exists demo_read  on raw.%I', t);
    execute format('drop policy if exists demo_write on raw.%I', t);
    execute format('create policy demo_read  on raw.%I for select to anon, authenticated using (true)', t);
    execute format('create policy demo_write on raw.%I for insert to anon, authenticated with check (true)', t);
  end loop;
end $$;

-- Bảng tĩnh trong mart cũng bật RLS (chỉ đọc) cho đồng bộ
alter table mart.audit_issues enable row level security;
drop policy if exists demo_read on mart.audit_issues;
create policy demo_read on mart.audit_issues for select to anon, authenticated using (true);
