table dq_fact_inventory
	lineageTag: 5c24bce1-0ae4-4d8a-b19f-863cc25f8c1c

	measure 'DQ Score INV' = DIVIDE ( COUNTROWS ( dq_fact_inventory ) - CALCULATE ( COUNTROWS ( dq_fact_inventory ), dq_fact_inventory[flag_dq_dirty] = TRUE ), COUNTROWS ( dq_fact_inventory ) )
		formatString: 0.00%
		lineageTag: 9fff1550-4437-48b9-af11-464a7dc1a460

	column month_end
		dataType: dateTime
		lineageTag: 0978e368-897d-4bbf-86fd-1098dc423536
		summarizeBy: none
		sourceColumn: month_end

	column item_code
		dataType: string
		isHidden
		lineageTag: 3f015dca-e2d8-4704-a513-49066c573372
		summarizeBy: none
		sourceColumn: item_code

	column warehouse_code
		dataType: string
		isHidden
		lineageTag: 4336fa1d-4eb9-4525-8d3c-9e437efb9fde
		summarizeBy: none
		sourceColumn: warehouse_code

	column on_hand_qty
		dataType: decimal
		lineageTag: a96c9970-051b-4cf9-bdd6-cd48bcc75cc1
		summarizeBy: none
		sourceColumn: on_hand_qty

	column safety_stock
		dataType: decimal
		lineageTag: de965fdf-c0d6-4b51-86c2-ec1c9cb4d076
		summarizeBy: none
		sourceColumn: safety_stock

	column last_receipt_date
		dataType: dateTime
		lineageTag: 27a998c6-faa2-4276-bd5a-e824d68b8b20
		summarizeBy: none
		sourceColumn: last_receipt_date

	column inventory_value_raw
		dataType: decimal
		lineageTag: b01739bb-ebc8-4d07-a78f-56ae1dd71022
		summarizeBy: none
		sourceColumn: inventory_value_raw

	column flag_negative_stock
		dataType: boolean
		lineageTag: 777889cc-d628-4f5c-aa6f-3ad80d692705
		summarizeBy: none
		sourceColumn: flag_negative_stock

	column flag_orphan_fk
		dataType: boolean
		lineageTag: 5a23a278-f364-4760-aeed-735cd2bf597c
		summarizeBy: none
		sourceColumn: flag_orphan_fk

	column flag_below_safety
		dataType: boolean
		lineageTag: 725f942e-26e7-45c9-bc5c-72e48271aab2
		summarizeBy: none
		sourceColumn: flag_below_safety

	column flag_dq_dirty
		dataType: boolean
		lineageTag: 12efecc6-767b-4a9a-ba2e-1f638d42deda
		summarizeBy: none
		sourceColumn: flag_dq_dirty

	partition dq_fact_inventory = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-0-ap-southeast-1.pooler.supabase.com:5432", "postgres"),
				    data = Source{[Schema="mart",Item="dq_fact_inventory"]}[Data]
				in
				    data

