table dq_inventory_recon
	lineageTag: 353eeb9b-7bde-40c4-99a2-695d32a0130c

	measure 'Inventory Recon Match Pct' = DIVIDE ( CALCULATE ( COUNTROWS ( dq_inventory_recon ), dq_inventory_recon[is_match] = TRUE ), COUNTROWS ( dq_inventory_recon ) )
		formatString: 0.00%
		lineageTag: ef51b169-eccb-4505-adc0-5023a234e3ce

	column month_end
		dataType: dateTime
		lineageTag: 85dbc2da-2c38-433e-b623-70511733f221
		summarizeBy: none
		sourceColumn: month_end

	column item_code
		dataType: string
		lineageTag: 9c674c2c-4091-473a-bec8-7f3c5b9aec3f
		summarizeBy: none
		sourceColumn: item_code

	column warehouse_code
		dataType: string
		lineageTag: 5ceab1a6-12b7-4fea-946b-83f49e019a78
		summarizeBy: none
		sourceColumn: warehouse_code

	column value_reported
		dataType: decimal
		lineageTag: afa7211b-7411-4311-9590-ddbab1327caf
		summarizeBy: none
		sourceColumn: value_reported

	column value_recomputed
		dataType: decimal
		lineageTag: 4831a00d-57b3-4ac3-a95a-69f017a720be
		summarizeBy: none
		sourceColumn: value_recomputed

	column is_match
		dataType: boolean
		lineageTag: bf9086f3-67df-4975-b506-21d3df96b705
		summarizeBy: none
		sourceColumn: is_match

	partition dq_inventory_recon = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-0-ap-southeast-1.pooler.supabase.com:5432", "postgres"),
				    data = Source{[Schema="mart",Item="dq_inventory_recon"]}[Data]
				in
				    data

