table fact_inventory
	lineageTag: 40de66e6-c835-470f-b60f-74f695cf09e3

	measure 'Inventory Value EOM' = CALCULATE ( SUM ( fact_inventory[inventory_value] ), fact_inventory[is_latest_eom] = TRUE )
		formatString: #,0
		lineageTag: 3e0f46a9-4910-46ef-a771-fdeb7d7b9fe7

	measure 'OnHandQty EOM' = CALCULATE ( SUM ( fact_inventory[on_hand_qty] ), fact_inventory[is_latest_eom] = TRUE )
		formatString: #,0
		lineageTag: 06300709-f456-4fa5-8e70-a43a0ea00030

	measure 'Discontinued Value' = CALCULATE ( [Inventory Value EOM], dim_product[item_status] = "Discontinued" )
		formatString: #,0
		lineageTag: ca77b14f-170f-4fb3-aec3-8a041b9dfb7a

	measure 'Discontinued Pct' = DIVIDE ( [Discontinued Value], CALCULATE ( [Inventory Value EOM], REMOVEFILTERS ( dim_product ) ) )
		formatString: 0.00%
		lineageTag: 4362d5ae-6e24-4376-b5e7-c9ca36b759df

	measure 'Negative Stock Rows' = CALCULATE ( COUNTROWS ( fact_inventory ), fact_inventory[flag_negative_stock] = TRUE, fact_inventory[is_latest_eom] = TRUE )
		formatString: #,0
		lineageTag: 0254a55f-b33d-47f2-a4c7-46974fa7581c

	measure 'Below Safety Rows' = CALCULATE ( COUNTROWS ( fact_inventory ), fact_inventory[flag_below_safety] = TRUE, fact_inventory[is_latest_eom] = TRUE )
		formatString: #,0
		lineageTag: 2e9fd79a-9b03-4ceb-8eba-11569199ddb1

	measure 'Max Discount Before Loss' = VAR lp = SELECTEDVALUE ( dim_product[list_price] ) VAR sc = SELECTEDVALUE ( dim_product[standard_cost] ) RETURN DIVIDE ( lp - sc, lp )
		formatString: 0.00%
		lineageTag: 77a33134-70b4-488a-b43b-affcaab74228

	measure 'Inv to Revenue Ratio' = DIVIDE ( [Inventory Value EOM], [Revenue Net] )
		formatString: 0.00
		lineageTag: 350bf3e2-c37c-4bd7-885b-04d9dab6d328

	measure 'Inventory Pct' = DIVIDE ( [Inventory Value EOM], CALCULATE ( [Inventory Value EOM], REMOVEFILTERS ( dim_category ) ) )
		formatString: 0.00%
		lineageTag: 76d2cb17-8731-4a28-ad28-3aad6f71621c

	column month_end
		dataType: dateTime
		lineageTag: a9d5655b-2204-4f70-bbc2-bdbc818275fa
		summarizeBy: none
		sourceColumn: month_end

	column month_start
		dataType: dateTime
		isHidden
		lineageTag: 130f3bf1-2701-4951-87eb-6196552a6f78
		summarizeBy: none
		sourceColumn: month_start

	column item_code
		dataType: string
		isHidden
		lineageTag: e7280b7e-db6f-4045-ac5b-517bd8bfb02d
		summarizeBy: none
		sourceColumn: item_code

	column warehouse_code
		dataType: string
		isHidden
		lineageTag: 6cb44823-58da-417d-9696-9ceb018355eb
		summarizeBy: none
		sourceColumn: warehouse_code

	column on_hand_qty
		dataType: decimal
		lineageTag: 65968a6f-9237-44e0-91b1-5742c09b46be
		summarizeBy: none
		sourceColumn: on_hand_qty

	column safety_stock
		dataType: decimal
		lineageTag: 8234cf5d-0d08-4046-a397-879cdb3f5752
		summarizeBy: none
		sourceColumn: safety_stock

	column last_receipt_date
		dataType: dateTime
		lineageTag: 525cd8a3-b950-42f1-b619-f273cb2f2ddc
		summarizeBy: none
		sourceColumn: last_receipt_date

	column days_since_receipt
		dataType: int64
		lineageTag: 2011be2a-6087-468d-ab80-878a5631d158
		summarizeBy: none
		sourceColumn: days_since_receipt

	column inventory_value
		dataType: decimal
		isHidden
		lineageTag: ca14f4fb-d661-463c-a1e3-8a26fb54731f
		summarizeBy: none
		sourceColumn: inventory_value

	column is_latest_eom
		dataType: boolean
		isHidden
		lineageTag: a06668d5-c4ba-470e-8631-bd3ab04902ab
		summarizeBy: none
		sourceColumn: is_latest_eom

	column flag_negative_stock
		dataType: boolean
		isHidden
		lineageTag: 91d6b5b6-5ce0-4f4e-90ef-dded3cbd341b
		summarizeBy: none
		sourceColumn: flag_negative_stock

	column flag_below_safety
		dataType: boolean
		isHidden
		lineageTag: dfb999f7-2ffa-4c1e-9c70-aeb7c989257e
		summarizeBy: none
		sourceColumn: flag_below_safety

	partition fact_inventory = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-0-ap-southeast-1.pooler.supabase.com:5432", "postgres"),
				    data = Source{[Schema="mart",Item="fact_inventory"]}[Data]
				in
				    data

