table fact_sales
	lineageTag: f400be07-791d-4ee0-98f1-b172a4f0903d

	measure 'Revenue Net' = CALCULATE ( SUM ( fact_sales[line_revenue] ), fact_sales[doc_status] <> "Cancelled" )
		formatString: #,0
		lineageTag: cc7f51e3-2468-4c44-9d6d-e74aa79ecbdd

	measure 'Revenue With Cost' = SUMX ( FILTER ( fact_sales, fact_sales[doc_status] <> "Cancelled" && NOT ISBLANK ( RELATED ( dim_product[standard_cost] ) ) ), fact_sales[line_revenue] )
		formatString: #,0
		lineageTag: 0870b694-f5cb-4d30-8416-4e413abfe757

	measure COGS = SUMX ( FILTER ( fact_sales, fact_sales[doc_status] <> "Cancelled" && NOT ISBLANK ( RELATED ( dim_product[standard_cost] ) ) ), fact_sales[qty_delivered] * RELATED ( dim_product[standard_cost] ) )
		formatString: #,0
		lineageTag: 024c057b-8e80-49b0-b38f-aa4faed61518

	measure 'Gross Margin' = [Revenue With Cost] - [COGS]
		formatString: #,0
		lineageTag: 2aef44cc-cfe4-4539-8826-377ee1eb1bf8

	measure 'Gross Profit' = [Gross Margin]
		formatString: #,0
		lineageTag: 9d9f36bf-d11e-4fae-9b86-db9167604421

	measure 'Gross Margin %' = DIVIDE ( [Gross Margin], [Revenue With Cost] )
		formatString: 0.00%
		lineageTag: 866d2de0-d6a2-4bc3-ad06-a5a17ce9ca7a

	measure 'Fill Rate' = DIVIDE ( CALCULATE ( SUM ( fact_sales[qty_delivered] ), fact_sales[doc_status] IN { "Completed", "Open" } ), CALCULATE ( SUM ( fact_sales[qty_order] ), fact_sales[doc_status] IN { "Completed", "Open" } ) )
		formatString: 0.00%
		lineageTag: c1a46680-443f-48bd-919a-200ae79321ec

	measure 'On-time Delivery' = VAR Delivered = FILTER ( fact_sales, NOT ISBLANK ( fact_sales[actual_delivery_date] ) ) RETURN DIVIDE ( COUNTROWS ( FILTER ( Delivered, fact_sales[actual_delivery_date] <= fact_sales[delivery_due_date] ) ), COUNTROWS ( Delivered ) )
		formatString: 0.00%
		lineageTag: 24296e89-6d86-4f97-b0e7-a3b9ca4a3aa8

	measure 'Avg Days Late' = AVERAGEX ( FILTER ( fact_sales, fact_sales[actual_delivery_date] > fact_sales[delivery_due_date] ), DATEDIFF ( fact_sales[delivery_due_date], fact_sales[actual_delivery_date], DAY ) )
		formatString: 0.0 "ngày"
		lineageTag: 73c4b2b8-0b48-453c-8acf-cec1a6d90eb0

	measure 'Avg Delivery Delay' = AVERAGEX ( FILTER ( fact_sales, NOT ISBLANK ( fact_sales[actual_delivery_date] ) ), DATEDIFF ( fact_sales[delivery_due_date], fact_sales[actual_delivery_date], DAY ) )
		formatString: 0.0 "ngày"
		lineageTag: 18c350cc-05ba-47dc-b511-1ab86db84828

	measure 'Return Value' = CALCULATE ( SUM ( fact_sales[line_revenue] ), fact_sales[doc_status] = "Return" )
		formatString: #,0
		lineageTag: 92ab2687-c5e2-4c3d-8ed8-c71a48564f39

	measure 'Return Rate' = DIVIDE ( -[Return Value], CALCULATE ( SUM ( fact_sales[line_revenue] ), fact_sales[doc_status] IN { "Completed", "Open" } ) )
		formatString: 0.00%
		lineageTag: c64d7144-2f37-40d5-ba07-71c744883e9d

	measure Target = SUM ( plan_monthly[target_revenue] )
		formatString: #,0
		lineageTag: a0f84d1b-976d-4837-9ab0-75d92ee69fac

	measure 'Revenue In Plan Scope' = CALCULATE ( [Revenue Net], fact_sales[in_plan_scope] = TRUE )
		formatString: #,0
		lineageTag: dc407c1e-0687-426a-9623-9f3c5f5effdc

	measure 'Pct of Plan' = DIVIDE ( [Revenue In Plan Scope], [Target] )
		formatString: 0.00%
		lineageTag: c3a3cc5c-4af1-41bd-a7bf-daf271de9148

	measure 'Achievement Index' = VAR RatioLocal = DIVIDE ( [Revenue In Plan Scope], [Target] ) VAR RatioGlobal = DIVIDE ( CALCULATE ( [Revenue In Plan Scope], REMOVEFILTERS ( dim_month ), REMOVEFILTERS ( dim_market_region ), REMOVEFILTERS ( dim_category ), REMOVEFILTERS ( dim_customer ), REMOVEFILTERS ( dim_product ) ), CALCULATE ( [Target], REMOVEFILTERS ( dim_month ), REMOVEFILTERS ( dim_market_region ), REMOVEFILTERS ( dim_category ) ) ) RETURN DIVIDE ( RatioLocal, RatioGlobal ) * 100
		formatString: 0.0
		lineageTag: 562f46b2-d61e-42eb-bde8-7d55c39ae100

	measure 'GM% Color' = VAR g = [Gross Margin %] RETURN SWITCH ( TRUE (), ISBLANK ( g ), "#9E9E9E", g < 0.13, "#C0392B", g < 0.16, "#E08E79", g < 0.19, "#BDC3C7", g < 0.21, "#7FB3D5", "#1F618D" )
		lineageTag: 876af32a-72b1-4d0d-9319-14a8d4d9e504

	measure 'Is Slow Heavy' = COALESCE ( SELECTEDVALUE ( item_moc[is_slow_heavy] ), FALSE )
		lineageTag: 47e5900a-3641-46e8-abaf-eb37c3056318

	column sales_sk
		dataType: int64
		isHidden
		lineageTag: eb423796-8b69-462a-940b-0fc647235ca8
		summarizeBy: none
		sourceColumn: sales_sk

	column src_row_index
		dataType: int64
		isHidden
		lineageTag: 40f62e26-dcb5-4db6-a0c3-1ab318542376
		summarizeBy: none
		sourceColumn: src_row_index

	column doc_date
		dataType: dateTime
		lineageTag: 06afdfcf-e359-46cb-876e-2094e9406f53
		summarizeBy: none
		sourceColumn: doc_date

	column month_start
		dataType: dateTime
		isHidden
		lineageTag: f6caca0b-5933-410b-836c-29bfa86bb2ea
		summarizeBy: none
		sourceColumn: month_start

	column order_no
		dataType: string
		lineageTag: 55ceec23-9677-429a-9001-5f79dc16ee19
		summarizeBy: none
		sourceColumn: order_no

	column line_no
		dataType: int64
		lineageTag: e7f6708e-21aa-4fc3-bbe2-417f5022ae4e
		summarizeBy: none
		sourceColumn: line_no

	column customer_code
		dataType: string
		isHidden
		lineageTag: bb181e9a-b7e1-4442-9d6d-32274e509546
		summarizeBy: none
		sourceColumn: customer_code

	column item_code
		dataType: string
		isHidden
		lineageTag: a102018b-fe16-473c-9bd8-51ba80dff71c
		summarizeBy: none
		sourceColumn: item_code

	column warehouse_code
		dataType: string
		isHidden
		lineageTag: ad784875-eaa0-4d52-9760-3087443261c4
		summarizeBy: none
		sourceColumn: warehouse_code

	column qty_order
		dataType: decimal
		lineageTag: 51c9c99e-5951-4b2e-bd8b-0bdf49b69e4b
		summarizeBy: none
		sourceColumn: qty_order

	column qty_delivered
		dataType: decimal
		lineageTag: 243d5df1-62a7-45af-a7ae-5087bd7ad990
		summarizeBy: none
		sourceColumn: qty_delivered

	column unit_price
		dataType: decimal
		lineageTag: e5104cec-c9a3-4795-b577-91e0cb934c07
		summarizeBy: none
		sourceColumn: unit_price

	column discount_pct
		dataType: decimal
		lineageTag: f7a083b1-5752-4714-9c10-b466ff43269d
		summarizeBy: none
		sourceColumn: discount_pct

	column doc_status
		dataType: string
		lineageTag: a99cbd55-1d1a-4327-b45c-3769c8c651ee
		summarizeBy: none
		sourceColumn: doc_status

	column delivery_due_date
		dataType: dateTime
		lineageTag: 453e2bf9-da95-4afa-9c8b-7695eb16a60d
		summarizeBy: none
		sourceColumn: delivery_due_date

	column actual_delivery_date
		dataType: dateTime
		lineageTag: 818e796c-87ab-47d8-9b10-d7c3f1bcff54
		summarizeBy: none
		sourceColumn: actual_delivery_date

	column salesperson
		dataType: string
		lineageTag: b62c9f2c-227b-4a7d-b555-35f3d995001d
		summarizeBy: none
		sourceColumn: salesperson

	column line_revenue
		dataType: decimal
		isHidden
		lineageTag: 02d8049a-6aef-49f1-adcb-6a8c6f334e32
		summarizeBy: none
		sourceColumn: line_revenue

	column in_plan_scope
		dataType: boolean
		isHidden
		lineageTag: 2a7c81c0-840b-4723-8d55-64fa4aab72a0
		summarizeBy: none
		sourceColumn: in_plan_scope

	column flag_orphan_fk
		dataType: boolean
		isHidden
		lineageTag: 814d9fb0-2000-429c-aa21-a2ad66d7f8e1
		summarizeBy: none
		sourceColumn: flag_orphan_fk

	column flag_zero_price
		dataType: boolean
		isHidden
		lineageTag: 003ac8e9-a902-47a8-855c-3f08e8d5a43a
		summarizeBy: none
		sourceColumn: flag_zero_price

	column flag_high_discount
		dataType: boolean
		isHidden
		lineageTag: c505b373-2a6d-467d-bb45-7d1dcb8c931d
		summarizeBy: none
		sourceColumn: flag_high_discount

	column flag_process_violation
		dataType: boolean
		isHidden
		lineageTag: df4298e3-7d1d-407c-98e5-5b858161f46b
		summarizeBy: none
		sourceColumn: flag_process_violation

	column flag_pv_discontinued_item
		dataType: boolean
		isHidden
		lineageTag: dd3b16ee-8f52-49e7-a302-8f19ce0759d3
		summarizeBy: none
		sourceColumn: flag_pv_discontinued_item

	column flag_pv_inactive_customer
		dataType: boolean
		isHidden
		lineageTag: d2a37224-06c1-4012-888b-04f7f596423b
		summarizeBy: none
		sourceColumn: flag_pv_inactive_customer

	column flag_pv_inactive_warehouse
		dataType: boolean
		isHidden
		lineageTag: 8298652b-ec66-4270-ba71-58f6498c9b1e
		summarizeBy: none
		sourceColumn: flag_pv_inactive_warehouse

	partition fact_sales = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-0-ap-southeast-1.pooler.supabase.com:5432", "postgres"),
				    data = Source{[Schema="mart",Item="fact_sales"]}[Data]
				in
				    data

